### ISSUE TITLE
BadImageFormatException on version 1.0.6

### ISSUE THREAD

**Issue by andreminelli** [rohankapoor/AutoPrompt#1]
Exception details:

"System.BadImageFormatException: Could not load file or assembly 'AutoPrompt, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'AutoPrompt, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'"

Downgrading to 1.0.5 works fine...

**Comment by rohankapoor** [comment]
Version 1.0.6 supports x64 platforms only. Are you seeing this on a x86 system?

**Comment by andreminelli** [comment]
No, it is a x64 system. But on Project properties, Build tab, the 'Prefer 32-bit' checkbox was checked.
I have unchecked and updated and now 1.0.6 is working.

Thanks!
